name: web

flutter:
  uses-material-design: true
  assets:
    - images/main_panel/
    - images/login/

description: An app built using Flutter for web

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^2.0.0
  protobuf: ^0.13.15

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
