name: web

flutter:
  uses-material-design: true
  assets:
    - create_presentation.png
    - google_icon.png
    - presentations_history.png
    - start_presentation.png
    - edit_presentation.png

description: An app built using Flutter for web

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: 2.1.2
  firebase_core: ^0.4.0+9
  protobuf: ^0.13.15
  http: 0.12.0+2
  json_serializable: 3.2.3
  google_sign_in: ^3.0.4
  firebase: ^5.0.0
  firebase_auth: 0.15.0+1
  image_picker: ^0.6.1
  path: ^1.3.9
  test: ^1.6.0
  service_worker: ^0.2.0
  build_runner: ^1.5.2
  build_web_compilers: ^2.1.1
  carousel_slider: ^1.3.0